kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: olm-certified-catalogs
spec:
  dockerImageRepository: registry.redhat.io/redhat/certified-operator-index
  lookupPolicy:
    local: true
  tags:
  - name: v4.8
    from:
      kind: DockerImage
      name: 'registry.redhat.io/redhat/certified-operator-index:v4.8'
    importPolicy:
      scheduled: true
    referencePolicy:
      type: Source